FROM python:3.11-slim
USER root

WORKDIR /opt/project

COPY python_packages.txt /opt/project/python_packages.txt
RUN pip install --no-cache-dir -r python_packages.txt

COPY . /opt/project/

CMD ["pytest", "-v", "/opt/project/tests"]